### ISSUE TITLE
Typo in code for Alice Desktop for macOS

### ISSUE THREAD

**Issue by scottprahl** [analogdevicesinc/alice#13]
Lines 334 and 335 in `alice-desktop-1.3-pyw (9-14-2020)` on the version-1.3 branch should read

    menubar = tkinter.Menu(root)
    appmenu = tkinter.Menu(menubar, name='apple')

This only affects macOS code since the windowing system must be `aqua`.  This has been validated under python 3.7.6 on macOS 10.14.6.

To support python2, then 334-335 looks like it might need to be

    if sys.version_info[0] == 2:
        menubar = tKinter.Menu(root)
        appmenu = tKinter.Menu(menubar, name='apple')
    else:
        menubar = tkinter.Menu(root)
        appmenu = tkinter.Menu(menubar, name='apple')

This is untested because my python 2.7.16 fails due to `pysmu` library issues.

**Comment by damercer** [comment]
Thanks for checking this out on Mac. I personally done own a Mac so some one else within the ADI software group would have needed to check.

Will incorporate in next release.

Doug

**Comment by damercer** [comment]
fixed in release 1.3.9
