### ISSUE TITLE
Branch 2.0 missing darwin case

### ISSUE THREAD

**Issue by scottprahl** [analogdevicesinc/alice#14]
at line 16139, `alice-desktop-1.3.pyw` on version-2.0 branch should add a case for macOS and return if not any of the systems.  This avoids trying to create a string with an uninitialized variable.

    elif platform.system() == "Darwin":
        if event.keycode == 0x7D: # increment digit for up arrow key
            NewVal = OldValfl + Step
        elif event.keycode == 0x7E: # decrement digit for down arrow
            NewVal = OldValfl - Step
        else:
            return
    else:
        return

**Comment by damercer** [comment]
Thanks for checking this out on Mac. I personally done own a Mac so some one else within the ADI software group would have needed to check.

Will incorporate in next release after testing.

Doug

**Comment by damercer** [comment]
Sorry but could you tell me which function this relates to? Line 16139 in the Version 1.3 branch, which contains last official alice-desktop-1.3.pyw, does not match anything related to the code snip-it you suggest adding.

Are you maybe looking at the ALICE source code for the M2k? That code is not being actively worked on at the moment.

Doug

**Comment by scottprahl** [comment]
Sorry.  Those line numbers are for the Version-2.0 branch (yes the file name is still `alice-desktop-1.3.pyw`).  

The same problem exists in the version-1.3 branch at 16399.  Just search for `platform.system`.

**Comment by damercer** [comment]
Fixed in release 1.3.9.
