### ISSUE TITLE
Not opening (Perhaps dual monitor problem?)

### ISSUE THREAD

**Issue by shlomitan** [analogdevicesinc/alice#16]
Windows 10, Alice 1.3

After using dual monitors, if Alice was on the secondary monitor when I closed it and later I open it when only one monitor is connected, I can't get it back to the single monitor.
This was a minor problem.

Now Alice won't open at all and appears like the attached screenshot. Clicking on the white boxes doesn't do anything. Connecting another monitor did not help.
The text from the command prompt is:

> Python 2.x
> Windowing System is win32
> No Device plugged IN!
> Skipping DestroyXYScreen()
> Skipping DestroyIAScreen()
> Skipping DestroySpectrumScreen()
> Skipping DestroyDacScreen()
> Skipping DestroyDigScreen()
> Skipping DestroyDigFiltScreen()
> Skipping DestroyMinigenScreen()
> Skipping DestroyMuxScreen()
> Skipping DestroyPhAScreen()
> Skipping DestroyBodeScreen()
> Skipping DestroyMeasuewScreen()
> Skipping DestroyETSScreen()
> Skipping cha_TC1Entry.delete(0,END)
> Skipping cha_TC1Entry.insert(4, 1.0)
> Skipping cha_TC2Entry.delete(0,END)
> Skipping cha_TC2Entry.insert(4, 1.0)
> Skipping chb_TC1Entry.delete(0,END)
> Skipping chb_TC1Entry.insert(4, 1.0)
> Skipping chb_TC2Entry.delete(0,END)
> Skipping chb_TC2Entry.insert(4, 1.0)
> Skipping cha_A1Entry.delete(0,END)
> Skipping cha_A1Entry.insert(4, 1.0)
> Skipping cha_A2Entry.delete(0,END)
> Skipping cha_A2Entry.insert(4, 1.0)
> Skipping chb_A1Entry.delete(0,END)
> Skipping chb_A1Entry.insert(4, 1.0)
> Skipping chb_A2Entry.delete(0,END)
> Skipping chb_A2Entry.insert(4, 1.0)
> Config File Not Found.
> C:\ALM Software\M1K\library.zip\numpy\core\_methods.py:59: RuntimeWarning: Mean of empty slice.
> C:\ALM Software\M1K\library.zip\numpy\core\_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "Tkinter.pyc", line 1547, in __call__
>   File "alice-desktop-1.3.pyw", line 19576, in CAresize
>   File "alice-desktop-1.3.pyw", line 5257, in UpdateTimeAll
>   File "alice-desktop-1.3.pyw", line 5266, in UpdateTimeScreen
>   File "alice-desktop-1.3.pyw", line 7248, in MakeTimeScreen
> NameError: global name 'CHABphase' is not defined

Opening Alice with ADALM1000 connected changes the log slightly but still doesn't work.
We had a problem with Alice crashing and only opening again when the card was disconnected, but this seems different.
I've uninstalled and reinstalled Alice with no avail.

Any help?
I'll gladly try anything and upload any log...

Thanks!
![Screen](https://user-images.githubusercontent.com/47846716/104125160-b2195280-535d-11eb-935f-8b78fbd10275.jpg)

**Comment by shlomitan** [comment]
OK, the problem was with alice-last-config.
I removed Alice and libsmu, deleted the Alice folder which contained only alice-last-config.cfg and reinstalled.
BTW - there's a problem with installing libsmu from the latest alice-desktop-1.3-libsmu-setup.exe because it looks for the wrong file. I downloaded libsmu separately aand installed.

Somehow now everything works.
What was wrong?

**Comment by damercer** [comment]
This is a known limitation.
In the alice-last-config file the screen coordinates for the windows are saved. When you use two monitors the screen coordinates for the monitor that was used are saved and if that screen space is gone the next time ALICE is started it will place the windows at the old coordinates which will be outside the new screen (single monitor in your example). I'm not sure how to detect when this happens. Any suggestions on how to know when the user changes number (or size for that matter) of monitors would be greatly appreciated.

Thanks
Doug

**Comment by Mateo1986** [comment]
I have a problem when trying to open the other applications that are installed with Alice I need to do an analysis with ADALM1000 and I need to measure the resistance in omhs and voltage at each point of a circuit but when trying to open these add-ons open and close immediately I think it is an error of the application or I do not know what it will be if you can help me to solve I would appreciate it is for a thesis work.

Translated with www.DeepL.com/Translator (free version)
![image](https://github.com/analogdevicesinc/alice/assets/160365347/350e7fca-64a0-4c55-992c-8794ac4971dd)
