### ISSUE TITLE
Alice has high CPU usage even when stopped

### ISSUE THREAD

**Issue by balbirthomas** [analogdevicesinc/alice#18]
## Issue
Alice desktop (python script) when launched has high CPU usage even when no acquisition is being done (i.e. "stop" button has be pressed). CPU usage is about 80-90% on the core that Alice is running on.

- I am using the latest version of Alice from this git repository (last git commit is dated 2022-01-26) from the `Version-1.3` branch.
- My platform is Linux.
- My Python version is 3.9.2

**Comment by damercer** [comment]
This is completely normal. The program sits in a very tight loop servicing any GUI events such as mouse or keyboard clicks. The program in not multi-threaded and the main loop serves both the GUI events and capturing data and re-drawing the screen (when Run is clicked) etc. The OS will interrupt as needed to use the CPU for other programs based on priority.

**Comment by balbirthomas** [comment]
Hi @damercer. Thank you for your response. I do not know the internals of Alice to dwell into details and you may very well be right.  If it is any help I did try a Python/Tk based application for another device -- [expeyes](https://github.com/expeyes/expeyes-programs.git) that I think is also single threaded. Attached is a screenshot of the application with output from `top`. 
![load](https://user-images.githubusercontent.com/1672069/157305983-6c835272-be49-4e75-b7dd-2cd41fa8c270.jpg)

However please do close the ticket if you feel that the particular nature of Alice precludes lower CPU usage.

**Comment by balbirthomas** [comment]
I did a bit of profiling using the `cProfile` module as in

```
python -m cProfile -o alice.log alice.py
```

[alice.log](https://github.com/analogdevicesinc/alice/files/8239580/alice.log) is attached.
Then I used the `pstats` to summarize the results of the 1 minute run of alice without any acquisition as in

```
import pstats
from pstats import SortKey
p = pstats.Stats('alice.log')
p.strip_dirs().sort_stats(-1).print_stats()
```
From the attached summary 
[stats.txt](https://github.com/analogdevicesinc/alice/files/8239584/stats.txt), given my limited knowledge of Alice's internals, the best I can infer is that the load seems to be generated by the `Analog_In()` method's call to `root.update()` and `root.update_idletasks()`. Perhaps this is what you may have referred to when you mentioned the "tight" event loop. Though I am a bit surprised that `Analog_In()` would still call `update` methods in the absence of any acquisition. 

PS: Is there any internals or developer documentation for Alice ? If I understood it a bit better I could do a deeper dive.

**Comment by damercer** [comment]
The “problem” has been identified and solved. Fixed version will be in next scheduled release. Releases are generally timed to the academic year (calendar).

Thanks for you interest.

**Comment by balbirthomas** [comment]
Using Alice Desktop Version 1.3.14 Dec 7 2022 I am no longer seeing high CPU usage and am hence closing this issue. Thank you very much.
