### ISSUE TITLE
Meter-Source 1.3 hangs in Win7Pro

### ISSUE THREAD

**Issue by SoCalIRL** [analogdevicesinc/alice#7]
Howdy folks, 

Am experiencing an issue on a recent install of 'alice-desktop-1.3-setup' on a Win7Pro system. 
I got over the initial libsmu issue, and a firmware hiccup, so everything seems to be talking for the most part. I'm now stepping through the 'Circuits 1' program ahead of hopefully referencing it for some teaching activities. Volt-Meter works fine, but Meter-Source hangs as soon as you click 'Run'. The configuration setting sent seems to get through (I'm going through the LED exercise and it does turn on) but no meter read data appears at any point. 

Any suggestions?

**Comment by damercer** [comment]
Sorry about that. That program does not get used much and there was an old change to libsmu that causes the issue you experienced. A corrected version of the source code has been committed to the alice 1.3 repository and the newly up-loaded version of the Windows executable installer release 1.1.5 should work now.

Thanks for checking / testing the software.

Doug

**Comment by SoCalIRL** [comment]
Perfect - working 100% now. 
Very much appreciated, and for what it's worth, tremendously impressed with both the unit itself and the curriculum materials available. It's an incredible resource.
